---
title: "Parches esenciales e importantes en la GAM"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    social: menu
    source: embed
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(esri2sf)

#--------------- URL de geoservicios --------------

# Bosque
url_agfs_bosque <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_parches_esenciales_importantes_bosque_gam/FeatureServer/0"

#---------------------- Datos ---------------------

# Objeto sf de bosque
sf_bosque = esri2sf(url_agfs_bosque)

#---------------- Paletas de colores ---------------

# Paleta para bosque
pal_bosque_d_PC <- colorNumeric(c("yellow", "red"), sf_bosque$d_PC)
pal_bosque_IF <- colorNumeric(c("yellow", "red"), sf_bosque$IF_)

```

### Parches esenciales para grupo funcional de bosque

```{r}
leaflet(data = sf_bosque) %>%
  setView(-84, 9.95, 10) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen, group = "Stamen") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    fillOpacity = 0.9,
    stroke = TRUE,
    color = ~pal_bosque_d_PC(d_PC),
    fillColor = ~pal_bosque_d_PC(d_PC),
    weight = 0.3,
    smoothFactor = 0.2,
    group = "Parches"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen", "Imágenes de ESRI"),
    overlayGroups = c("Parches"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addLegend(
    position = "bottomright",
    pal=pal_bosque_d_PC,
    values = ~d_PC, 
    group = "Parches",
    title = "Esencialidad"
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomright",
    options = scaleBarOptions(imperial = FALSE)
  )
```

***
Parches esenciales para grupo funcional de bosque...  
[Dirección del geoservicio](https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_parches_esenciales_importantes_bosque_gam/FeatureServer/0)

### Parches importantes para grupo funcional de bosque

```{r}
leaflet(data = sf_bosque) %>%
  setView(-84, 9.95, 10) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen, group = "Stamen") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    fillOpacity = 0.9,
    stroke = TRUE,
    color = ~pal_bosque_IF(IF_),
    fillColor = ~pal_bosque_IF(IF_),
    weight = 0.3,
    smoothFactor = 0.2,
    group = "Parches"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen", "Imágenes de ESRI"),
    overlayGroups = c("Parches"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addLegend(
    position = "bottomright",
    pal=pal_bosque_IF,
    values = ~IF_, 
    group = "Parches",
    title = "Importancia"
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomright",
    options = scaleBarOptions(imperial = FALSE)
  )
```

***
Parches importantes para grupo funcional de bosque...  
[Dirección del geoservicio](https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_parches_esenciales_importantes_bosque_gam/FeatureServer/0)